import {
  breakpoints,
  density,
  elevation,
  fonts,
  motion,
  radius,
  spacing,
  typeScale,
  zIndex,
} from './scales.js';
import { overlay, semanticTokens } from './semantic.js';

const px = (n: number) => `${String(n)}px`;
const block = (selector: string, vars: Record<string, string>, extra = '') =>
  `${selector} {\n${extra}${Object.entries(vars)
    .map(([k, v]) => `  --${k}: ${v};`)
    .join('\n')}\n}\n`;

function densityVars(mode: keyof typeof density): Record<string, string> {
  const d = density[mode];
  return {
    'row-height': px(d['row-height']),
    'control-height': px(d['control-height']),
    'page-padding': px(d['page-padding']),
    'card-padding': px(d['card-padding']),
    'field-gap': px(d['field-gap']),
    'kanban-card-padding': px(d['kanban-card-padding']),
    'font-body-size': px(d.body[0]),
    'font-body-lh': px(d.body[1]),
    'font-body-sm-size': px(d['body-sm'][0]),
    'font-body-sm-lh': px(d['body-sm'][1]),
    'font-cell-size': px(d.cell[0]),
    'font-cell-lh': px(d.cell[1]),
  };
}

function themeVars(theme: 'light' | 'dark'): Record<string, string> {
  return {
    ...semanticTokens[theme],
    overlay: overlay[theme],
    ...Object.fromEntries(Object.entries(elevation[theme]).map(([k, v]) => [`elevation-${k}`, v])),
  };
}

/**
 * Render every design token as CSS custom properties (§9). Light is the default; dark applies
 * with data-theme="dark", or data-theme="system" when the OS prefers dark. Density applies via
 * data-density. The output is committed as src/styles/tokens.css and checked by a test.
 */
export function renderTokensCss(): string {
  const constants: Record<string, string> = {
    'font-family-sans': fonts.sans,
    'font-family-mono': fonts.mono,
    ...Object.fromEntries(
      Object.entries(typeScale).flatMap(([name, [size, lh, weight]]) => [
        [`type-${name}-size`, px(size)],
        [`type-${name}-lh`, px(lh)],
        [`type-${name}-weight`, String(weight)],
      ]),
    ),
    ...Object.fromEntries(spacing.map((v, i) => [`space-${String(i)}`, px(v)])),
    ...Object.fromEntries(Object.entries(radius).map(([k, v]) => [`r-${k}`, px(v)])),
    'duration-fast': `${String(motion.duration.fast)}ms`,
    'duration-base': `${String(motion.duration.base)}ms`,
    'duration-slow': `${String(motion.duration.slow)}ms`,
    'motion-ease-standard': motion.easing.standard,
    'motion-ease-exit': motion.easing.exit,
    ...Object.fromEntries(Object.entries(zIndex).map(([k, v]) => [`z-${k}`, String(v)])),
    ...Object.fromEntries(Object.entries(breakpoints).map(([k, v]) => [`bp-${k}`, px(v)])),
  };

  return [
    '/* GENERATED by @sm/ui (src/tokens/css.ts). Do not edit: change the TypeScript tokens and run `pnpm --filter @sm/ui tokens`. */\n',
    block(
      ':root',
      { ...constants, ...themeVars('light'), ...densityVars('default') },
      '  color-scheme: light;\n',
    ),
    block(":root[data-theme='dark']", themeVars('dark'), '  color-scheme: dark;\n'),
    `@media (prefers-color-scheme: dark) {\n${block(
      ":root[data-theme='system']",
      themeVars('dark'),
      '  color-scheme: dark;\n',
    )
      .split('\n')
      .map((l) => (l ? `  ${l}` : l))
      .join('\n')}}\n`,
    block(":root[data-density='comfortable']", densityVars('comfortable')),
    block(":root[data-density='compact']", densityVars('compact')),
    // Arabic needs ~10% more line height (§9.12 rule 6).
    `:root[lang|='ar'] {\n  --arabic-leading-boost: 1.1;\n}\n`,
  ].join('\n');
}
